export const ACCENTS = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Argentinian',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusan',
  'Belarusian',
  'Belgian',
  'Belizian',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinese',
  'Burmese',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Congolese',
  'Costa Rican',
  'Croat',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dominican',
  'Ecuadorean',
  'Egyptian',
  'Salvadorean',
  'Emirati',
  'English',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Dutch',
  'Honduran',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Kuwaiti',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Liechtenstein',
  'Lithuanian',
  'Luxembourg',
  'Macedonian',
  'Madagascan',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Moldovan',
  'Monacan',
  'Monégasque',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nepalese',
  'Dutch',
  'New Zealand',
  'Nicaraguan',
  'Nigerien',
  'Nigerian',
  'North Korean',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Philippine',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saudi',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serb',
  'Serbian',
  'Seychellois',
  'Sierra Leonian',
  'Singaporean',
  'Slovak',
  'Slovene',
  'Slovenian',
  'Solomon Islands',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tadjik',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Trinidadian',
  'Tobagan',
  'Tobagonian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Turkoman',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Vanuatuan',
  'Vatican City',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Western Samoan',
  'Yemeni',
  'Yugoslav',
  'Zaïrean',
  'Zambian',
  'Zimbabwean',
];

export const COUNTRY_ACCENTS_MAP: Map<string, string> = new Map<string, string>([
  ['Afghanistan', 'Afghan'],
  ['Albania', 'Albanian'],
  ['Algeria', 'Algerian'],
  ['Angola', 'Angolan'],
  ['Antarctica', 'Antarctic'],
  ['Argentina', 'Argentinian'],
  ['Armenia', 'Armenian'],
  ['Australia', 'Australian'],
  ['Austria', 'Austrian'],
  ['Azerbaijan', 'Azerbaijani'],
  ['Bangladesh', 'Bangladeshi'],
  ['Belarus', 'Belarusian'],
  ['Belgium', 'Belgian'],
  ['Belize', 'Belizian'],
  ['Benin', 'Beninese'],
  ['Bermuda', 'Bermudian'],
  ['Bhutan', 'Bhutanese'],
  ['Bolivia', 'Bolivian'],
  ['Bosnia and Herzegovina', 'Bosnian'],
  ['Botswana', 'Botswanan'],
  ['Brazil', 'Brazilian'],
  ['Brunei', 'Bruneian'],
  ['Bulgaria', 'Bulgarian'],
  ['Burkina Faso', 'Burkinese'],
  ['Burundi', 'Burundian'],
  ['Cambodia', 'Cambodian'],
  ['Cameroon', 'Cameroonian'],
  ['Canada', 'Canadian'],
  ['Central African Republic', 'Central African Republic'],
  ['Chad', 'Chadian'],
  ['Chile', 'Chilean'],
  ['China', 'Chinese'],
  ['Colombia', 'Colombian'],
  ['Costa Rica', 'Costa Rican'],
  ['Croatia', 'Croatian'],
  ['Cuba', 'Cuban'],
  ['Cyprus', 'Cypriot'],
  ['Czech Republic', 'Czech'],
  ['Democratic Republic of the Congo', 'Congolese'],
  ['Denmark', 'Danish'],
  ['Djibouti', 'Djiboutian'],
  ['Dominican Republic', 'Dominican'],
  ['East Timor', 'East Timorese'],
  ['Ecuador', 'Ecuadorean'],
  ['Egypt', 'Egyptian'],
  ['El Salvador', 'Salvadorean'],
  ['Equatorial Guinea', 'Equatorial Guinean'],
  ['Eritrea', 'Eritrean'],
  ['Estonia', 'Estonian'],
  ['Ethiopia', 'Ethiopian'],
  ['Falkland Islands', 'Falkland Islands'],
  ['Fiji', 'Fijian'],
  ['Finland', 'Finnish'],
  ['France', 'French'],
  ['French Guiana', 'French Guianese'],
  ['French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'],
  ['Gabon', 'Gabonese'],
  ['Gambia', 'Gambian'],
  ['Georgia', 'Georgian'],
  ['Germany', 'German'],
  ['Ghana', 'Ghanaian'],
  ['Greece', 'Greek'],
  ['Greenland', 'Greenlandic'],
  ['Guatemala', 'Guatemalan'],
  ['Guinea', 'Guinean'],
  ['Guinea Bissau', 'Guinean'],
  ['Guyana', 'Guyanese'],
  ['Haiti', 'Haitian'],
  ['Honduras', 'Honduran'],
  ['Hungary', 'Hungarian'],
  ['Iceland', 'Icelandic'],
  ['India', 'Indian'],
  ['Indonesia', 'Indonesian'],
  ['Iran', 'Iranian'],
  ['Iraq', 'Iraqi'],
  ['Ireland', 'Irish'],
  ['Israel', 'Israeli'],
  ['Italy', 'Italian'],
  ['Ivory Coast', 'Ivory Coast'],
  ['Jamaica', 'Jamaican'],
  ['Japan', 'Japanese'],
  ['Jordan', 'Jordanian'],
  ['Kazakhstan', 'Kazakh'],
  ['Kenya', 'Kenyan'],
  ['Kosovo', 'Kosovan'],
  ['Kuwait', 'Kuwaiti'],
  ['Kyrgyzstan', 'Kyrgyzstani'],
  ['Laos', 'Laotian'],
  ['Latvia', 'Latvian'],
  ['Lebanon', 'Lebanese'],
  ['Lesotho', 'Lesothan'],
  ['Liberia', 'Liberian'],
  ['Libya', 'Libyan'],
  ['Lithuania', 'Lithuanian'],
  ['Luxembourg', 'Luxembourg'],
  ['Macedonia', 'Macedonian'],
  ['Madagascar', 'Madagascan'],
  ['Malawi', 'Malawian'],
  ['Malaysia', 'Malaysian'],
  ['Mali', 'Malian'],
  ['Malta', 'Maltese'],
  ['Mauritania', 'Mauritanian'],
  ['Mexico', 'Mexican'],
  ['Moldova', 'Moldovan'],
  ['Mongolia', 'Mongolian'],
  ['Montenegro', 'Montenegrin'],
  ['Morocco', 'Moroccan'],
  ['Mozambique', 'Mozambican'],
  ['Myanmar', 'Myanmarese'],
  ['Namibia', 'Namibian'],
  ['Nepal', 'Nepalese'],
  ['Netherlands', 'Dutch'],
  ['New Caledonia', 'New Caledonian'],
  ['New Zealand', 'New Zealand'],
  ['Nicaragua', 'Nicaraguan'],
  ['Niger', 'Nigerien'],
  ['Nigeria', 'Nigerian'],
  ['North Korea', 'North Korean'],
  ['Northern Cyprus', 'Northern Cypriot'],
  ['Norway', 'Norwegian'],
  ['Oman', 'Omani'],
  ['Pakistan', 'Pakistani'],
  ['Panama', 'Panamanian'],
  ['Papua New Guinea', 'Papua New Guinean'],
  ['Paraguay', 'Paraguayan'],
  ['Peru', 'Peruvian'],
  ['Philippines', 'Philippine'],
  ['Poland', 'Polish'],
  ['Portugal', 'Portuguese'],
  ['Puerto Rico', 'Puerto Rican'],
  ['Qatar', 'Qatari'],
  ['Republic of Serbia', 'Serbian'],
  ['Republic of the Congo', 'Congolese'],
  ['Romania', 'Romanian'],
  ['Russia', 'Russian'],
  ['Rwanda', 'Rwandan'],
  ['Saudi Arabia', 'Saudi Arabian'],
  ['Senegal', 'Senegalese'],
  ['Sierra Leone', 'Sierra Leonian'],
  ['Slovakia', 'Slovak'],
  ['Slovenia', 'Slovenian'],
  ['Solomon Islands', 'Solomon Islands'],
  ['Somalia', 'Somali'],
  ['Somaliland', 'Somalilander'],
  ['South Africa', 'South African'],
  ['South Korea', 'South Korean'],
  ['South Sudan', 'South Sudanese'],
  ['Spain', 'Spanish'],
  ['Sri Lanka', 'Sri Lankan'],
  ['Sudan', 'Sudanese'],
  ['Suriname', 'Surinamese'],
  ['Swaziland', 'Swazi'],
  ['Sweden', 'Swedish'],
  ['Switzerland', 'Swiss'],
  ['Syria', 'Syrian'],
  ['Taiwan', 'Taiwanese'],
  ['Tajikistan', 'Tajik'],
  ['Thailand', 'Thai'],
  ['The Bahamas', 'Bahamian'],
  ['Togo', 'Togolese'],
  ['Trinidad and Tobago', 'Trinidadian'],
  ['Tunisia', 'Tunisian'],
  ['Turkey', 'Turkish'],
  ['Turkmenistan', 'Turkmen'],
  ['Uganda', 'Ugandan'],
  ['Ukraine', 'Ukrainian'],
  ['United Arab Emirates', 'Emirati'],
  ['United Kingdom', 'British'],
  ['United Republic of Tanzania', 'Tanzanian'],
  ['United States of America', 'American'],
  ['Uruguay', 'Uruguayan'],
  ['Uzbekistan', 'Uzbek'],
  ['Vanuatu', 'Vanuatuan'],
  ['Venezuela', 'Venezuelan'],
  ['Vietnam', 'Vietnamese'],
  ['West Bank', 'West Bank'],
  ['Western Sahara', 'Western Saharan'],
  ['Yemen', 'Yemeni'],
  ['Zambia', 'Zambian'],
  ['Zimbabwe', 'Zimbabwean']
]);

export const NATIVE_ACCENTS = [{
    name: 'British Isles',
    children: [{
        name: 'England',
      },{
        name: 'Scotland',
      },{
        name: 'Wales',
      },{
        name: 'Isle of Man',
      },{
        name: 'Ireland',
        children: [{
            name: 'Ulster',
          },{
            name: 'Connacht, Leinster, and Munster',
          },{
            name: 'Irish Travellers',
          },
        ],
      },
    ],
  },{
    name: 'North America',
    children: [{
        name: 'Canada',
      },{
        name: 'United States',
      },{
        name: 'West Indies and Bermuda',
      },
    ],
  },{
    name: 'Oceania',
    children: [{
        name: 'Australia',
      },{
        name: 'New Zealand',
      },{
        name: 'Norfolk Island and Pitcairn',
      },
    ],
  },{
    name: 'Africa and the Atlantic',
    children: [{
        name: 'South Atlantic',
        children: [{
            name: 'Falkland Islands',
          },{
            name: 'Saint Helena',
          },
        ],
      },{
        name: 'Southern Africa',
        children: [{
            name: 'South Africa',
          },{
            name: 'Zimbabwe',
          },{
            name: 'Namibia',
          },
        ],
      },
    ],
  },{
    name: 'Asia',
    children: [{
        name: 'India and South Asia',
      },{
        name: 'Philippines',
      },{
        name: 'Hong Kong',
      },{
        name: 'Malaysia',
      },{
        name: 'Singapore',
      },
    ],
  },
];
